name: Push Content to Another Repo

on:
  push:
    branches:
      - main  

jobs:
  push-content:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repo
      uses: actions/checkout@v2
      with:
        repository: PD-NET/Devnew  # Replace 'owner/source-repo' with the source repository in the format 'owner/repo'
        ref: main  # Replace 'main' with the branch you want to clone

    - name: Configure Git
      run: |
        git config --global user.email "eng21ct0006@dsu.edu.in"
        git config --global user.name "Gaurang-dsu"

    - name: Push to Destination Repo
      run: |
        git remote add destination-repo https://<Gaurang-dsu>:<PAT_ACCESS_KEY>@github.com/PD-NET/test
        git push destination-repo main
