name: Push to Another Repository

on:
  push:
    branches:
      - main  # Replace with the source branch you want to trigger the workflow
permissions: write-all
jobs:
  push_code_from_test_to_prod:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write 

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: README file
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
         API_TOKEN_GITHUB: ${{ secrets.PAT_ACCESS_KEY}} # Use the orrect environment variable name
        with:
          source_file: 'README.md'
          destination_repo: 'PD-Net/test'
          user_email: 'eng21ct0006@dsu.edu.in'
          user_name: 'Gaurang-dsu'
            
      - name: client code
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
         API_TOKEN_GITHUB: ${{ secrets.PAT_ACCESS_KEY }} # Use the correct environment variable name
        with:
          source_file: 'client/'
          destination_repo: 'PD-Net/test'
          user_email: 'eng21ct0006@dsu.edu.in'
          user_name: 'Gaurang-dsu'

      - name: python file
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
         API_TOKEN_GITHUB: ${{ secrets.PAT_ACCESS_KEY }} # Use the correct environment variable name
        with:
          source_file: 'hello.py'
          destination_repo: 'PD-Net/test'
          user_email: 'eng21ct0006@dsu.edu.in'
          user_name: 'Gaurang-dsu'
