name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
           
  push-dev-to-test-repo:
   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'PD-NET/test'
        ref: main-test
        token: ${{ secrets.PAT_ACCESS_KEY }}

    - name: Add dev repo and pull to test repo
      run: |
        
        git remote add dev https://github.com/PD-NET/Devnew.git
        git remote -v
        git branch -a
        git config user.name Gaurang-dsu
        git config user.email eng21ct0006@dsu.edu.in
        
        git pull dev main
        #We use pull here to pull to the local system but when we need to push it to the remote repo ,we use push
        #hence pull and push is used here
        git push 
      
