name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PAT_ACCESS_KEY }}
      with:

        source_file: 'node_modules/.'
        destination_repo: 'PD-NET/test'
        

        user_email: 'eng21ct0006@dsu.edu.in'
        user_name: 'Gaurang-dsu'
        commit_message: 'successful push'
