name: Push to Other Repos

on:
  push:
    branches:
      - main

jobs:
  push_to_repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2

    - name: Set up Git credentials
      run: |
        git config user.email "eng21ct0006@dsu.edu.in"
        git config user.name "Gaurang-dsu"

    - name: Push to destination repository 1
      run: |
        destination_repo_1="https://github.com/PD-NET/test.git"
        git clone "$destination_repo_1" destination_1
        rsync -av --exclude=destination_1/* --exclude=.git/ * destination_1/
        cd destination_1
        git add .
        git commit -m "Automated update from source repository"
        git push origin main
