name: ZAP Scan

on:
  push:
    branches:
      - main
      
jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      TARGET_URL: ${{ secrets.TARGET_URL }}
      ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run ZAP Scan
      run: python security.py
      env:
        TARGET_URL: ${{ env.TARGET_URL }}
        ZAP_API_KEY: ${{ env.ZAP_API_KEY }}
