name: OWASP ZAP Integration with GitHub Actions

on:
  push:
    branches:
      - main  # Specify the branch to trigger the workflow

jobs:
  zap_scan:
    name: Scan the web application
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          target: 'http://testphp.vulnweb.com/'
