name: OWASP ZAP Integration with GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  DAST-testing-with-OWASP-ZAP:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "main"
         
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          sudo pip install -r requirements.txt
          sudo python app.py &

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
         target: 'http://127.0.0.1:8081'
         artifact_name: 'DAST-results-zap_scan'
         
      - name : Exit ZAP
        run: exit 0
