name: OWASP ZAP Integration with GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

permissions:
    actions: read
    contents: read
    security-events: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: zap_scan
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://pd-net-prod-main-1518350640.us-east-1.elb.amazonaws.com/'
          cmd_options: '-a'
          artifact_name: 'DAST-results-zap_scan'
