name: Wapiti Report Workflow

on:
  push:
    branches:
      - main  # Replace with your branch name if needed

jobs:
  wapiti-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Wapiti Scan
        run: |
          sudo apt-get update
          sudo apt-get install -y wapiti


      - name: Run Wapiti scan
        run: |
         wapiti -u http://pd-net-prod-main-1518350640.us-east-1.elb.amazonaws.com/ -o wapiti-report.html


      - name: Upload Wapiti Report
        uses: actions/upload-artifact@v2
        with:
          name: wapiti-report
          path: wapiti-report.html
