wapiti_scan:
   name: Wapiti DAST Scan
   runs-on: ubuntu-latest
   needs: [analyze]
   permissions:
     contents: read

   steps:
   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Install Wapiti
     run: |
      sudo apt-get update
      sudo apt-get install -y wapiti

   - name: Run Wapiti scan
     run: |
      wapiti -u http://pd-net-prod-main-1518350640.us-east-1.elb.amazonaws.com/ -o wapiti-report.html

   - name: Upload Wapiti HTML report
     uses: actions/upload-artifact@v2
     with:
       name: wapiti-report
       path: wapiti-report.html
